apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tools
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: https://github.com/ae-business-solutions/CD-k8s-demo
    targetRevision: HEAD
    path: cluster/argocd

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: https://github.com/ae-business-solutions/CD-k8s-demo
    targetRevision: HEAD
    path: cluster/ingress

  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: certmanager
#   namespace: argocd
# spec:
#   project: tools
#   source:
#     repoURL: https://github.com/ae-business-solutions/CD-k8s-demo
#     targetRevision: HEAD
#     path: cluster/cert-manager

#   destination: 
#     server: https://kubernetes.default.svc
#     namespace: cert-manager

#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true

#     automated:
#       selfHeal: true
#       prune: true